### PR TITLE
Add a defcustom in order to avoid jumping forward after REPL evaluation

### PR DESCRIPTION
**Pull request by arichiardi**
As per my opened issue #4.
I am not an elisp expert so please advice if we can improve it.

### CODE REVIEW

**Comment by kaz-yos** [comment]
I have incorporated the suggested changes. I didn't pull this directly because I like to work on a separate branch before merging into the production branch. Please configure the ```eir-jump-after-eval``` variable to nil for the wanted behavior. It is currently only available for lisp languages.

https://github.com/kaz-yos/eval-in-repl/blob/master/eval-in-repl.el#L77-L83

**Comment by arichiardi** [comment]
Great no problem, I will sync to ```master```. I am going to answer to the other one.

**Comment by kaz-yos** [comment]
This has been implemented for other languages in version 0.7.0. Also I realized this can be temporarily reversed using ```let```. An example for the shell version is the following.

```lisp
;; Version with opposite behavior to eir-jump-after-eval configuration
(defun eir-eval-in-shell2 ()
  "eval-in-repl for shell script (opposite behavior)

This version has the opposite behavior to the eir-jump-after-eval
configuration when invoked to evaluate a line."
  (interactive)
  (let ((eir-jump-after-eval (not eir-jump-after-eval)))
       (eir-eval-in-shell)))
(add-hook 'sh-mode-hook
          '(lambda()
         (local-set-key (kbd "C-M-<return>") 'eir-eval-in-shell2)))
```

**Comment by arichiardi** [comment]
So no more defcustom? Sorry I did not understand the current state of the feature

**Comment by kaz-yos** [comment]
The ```defcustom``` you contributed is still available as it was before. In addition, now it is active for other languages, too.

I just showed a use case of the ```defcustom``` variable. By temporarily reassigning ```eir-jump-after-eval``` variable using ```let```, the behavior can be modified temporarily (jump when global setting is no jumping or the other way around).

**Comment by arichiardi** [comment]
Ah ok sorry, I did not read the code :ashamed: :smile:

**Pull request closed without merging**
