### PR TITLE
 add JavaScript support with js-comint.

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by stardiviner** [comment]
I tested on my machine.

**Comment by stardiviner** [comment]
@kaz-yos Can you accept my pull request?

**Comment by kaz-yos** [comment]
I'm sorry for being slow. I have very little experience with Javascript. Which execution environment outside emacs do I need to run the repl via js3-mode, js2-mode, and js-comint? Is it node.js or do I connect to Firefox MozRepl?

**Comment by kaz-yos** [comment]
I installed the dependencies and Node.js via homebrew to have the node executable. The repl has name "*js*" rather than "*javascript*", also I'm having broken is this the execution environment you use?

**Comment by stardiviner** [comment]
Linux install: `rhino`, `nodejs`,  Run js-comint with `run-js`, test with input `1 + 1`.
Yes, the repl buffer name is `*js*`. You might need to adjust environment path if your Emacs can't find executable.

**Comment by stardiviner** [comment]
Do I need to add package dependency to `eval-in-repl-pkg.el`?

**Comment by kaz-yos** [comment]
I can work from here, I think. There are some tweaks necessary, so I won't be directly merging your request, but will include the file submitted after some modifications.

**Comment by kaz-yos** [comment]
The suggestion was incorporated as follows.

https://github.com/kaz-yos/eval-in-repl/commit/1b3ab7d73bf211ae1f6bd6d6fb75d6e52010f101

**Pull request closed without merging**
